//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeTai()
        {
            this.DSNguoiThamGiaDeTais = new HashSet<DSNguoiThamGiaDeTai>();
            this.KinhPhiDeTais = new HashSet<KinhPhiDeTai>();
            this.BaiBaos = new HashSet<BaiBao>();
        }
    
        public string MaDeTai { get; set; }
        public string MaDeTaiHoSo { get; set; }
        public string TenDeTai { get; set; }
        public string MaLoaiDeTai { get; set; }
        public string MaCapDeTai { get; set; }
        public string MaDVChuTri { get; set; }
        public string MaDonViQLThucHien { get; set; }
        public string MaLinhVuc { get; set; }
        public string MucTieuDeTai { get; set; }
        public string NoiDungDeTai { get; set; }
        public string KetQuaDeTai { get; set; }
        public Nullable<System.DateTime> NamBD { get; set; }
        public Nullable<System.DateTime> NamKT { get; set; }
        public string MaXepLoai { get; set; }
        public string MaTinhTrang { get; set; }
        public string MaPhanLoaiSP { get; set; }
        public string KinhPhi { get; set; }
        public string LienKetWeb { get; set; }
        public string LinkFileUpload { get; set; }
    
        public virtual CapDeTai CapDeTai { get; set; }
        public virtual LoaiHinhDeTai LoaiHinhDeTai { get; set; }
        public virtual DonViChuTri DonViChuTri { get; set; }
        public virtual DonViQL DonViQL { get; set; }
        public virtual LinhVuc LinhVuc { get; set; }
        public virtual XepLoai XepLoai { get; set; }
        public virtual TinhTrangDeTai TinhTrangDeTai { get; set; }
        public virtual PhanLoaiSP PhanLoaiSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSNguoiThamGiaDeTai> DSNguoiThamGiaDeTais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KinhPhiDeTai> KinhPhiDeTais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiBao> BaiBaos { get; set; }
    }
}
