//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSBaiBaoDeTai
    {
        public int MaDeTai { get; set; }
        public int MaBaiBao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BaiBao BaiBao { get; set; }
        public virtual DeTai DeTai { get; set; }
    }
}
