//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class KinhPhiDeTai
    {
        public int MaPhi { get; set; }
        public string MaDeTai { get; set; }
        public string LoaiKinhPhi { get; set; }
        public Nullable<System.DateTime> NamTiepNhan { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string LoaiTien { get; set; }
    
        public virtual DeTai DeTai { get; set; }
    }
}
