//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string Usernames { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> MaNKH { get; set; }
        public Nullable<int> MaChucNang { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
    }
}
