//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSNguoiThamGiaBaiBao
    {
        public int MaTT { get; set; }
        public int MaBaiBao { get; set; }
        public int MaNKH { get; set; }
        public Nullable<bool> LaTacGiaChinh { get; set; }
        public string NhiemVu { get; set; }
    
        public virtual BaiBao BaiBao { get; set; }
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
    }
}
