//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSPhatMinhNKH
    {
        public int MaTT { get; set; }
        public Nullable<int> MaNKH { get; set; }
        public Nullable<int> MaPM { get; set; }
        public Nullable<bool> LaChuSoHuu { get; set; }
        public string VaiTro { get; set; }
    
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
        public virtual PhatMinhGiaiPhap PhatMinhGiaiPhap { get; set; }
    }
}
