//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganHangNKH
    {
        public int MaNKH { get; set; }
        public string STKNH { get; set; }
        public Nullable<int> MaNH { get; set; }
        public string ChiNhanhNH { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NganHang NganHang { get; set; }
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
    }
}
