//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgoaiNguNKH
    {
        public int ID { get; set; }
        public int MaNKH { get; set; }
        public int MaTrinhDoNN { get; set; }
        public Nullable<int> Doc { get; set; }
        public Nullable<int> Viet { get; set; }
        public Nullable<int> Noi { get; set; }
    
        public virtual DanhGiaNgoaiNgu DanhGiaNgoaiNgu { get; set; }
        public virtual DanhGiaNgoaiNgu DanhGiaNgoaiNgu1 { get; set; }
        public virtual DanhGiaNgoaiNgu DanhGiaNgoaiNgu2 { get; set; }
        public virtual TrinhDoNgoaiNgu TrinhDoNgoaiNgu { get; set; }
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
    }
}
