//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaKhoaHoc_KH
    {
        public int MaNKH { get; set; }
        public string HuongNghienCuu { get; set; }
        public string GiaiThuong { get; set; }
        public string ThamGiaToChu { get; set; }
    
        public virtual NhaKhoaHoc NhaKhoaHoc { get; set; }
    }
}
