//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLKhoaHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhatMinhGiaiPhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhatMinhGiaiPhap()
        {
            this.DSPhatMinhNKHs = new HashSet<DSPhatMinhNKH>();
        }
    
        public int MaPM { get; set; }
        public string TenPM { get; set; }
        public string SoHieuPM { get; set; }
        public string MotaPM { get; set; }
        public string DoiTuongSuDung { get; set; }
        public string QuocGiaCap { get; set; }
        public string LinkLienKet { get; set; }
        public byte[] AnhScanGiayChungNhan { get; set; }
        public byte[] AnhChupSanPham1 { get; set; }
        public byte[] AnhChupSanPham2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DSPhatMinhNKH> DSPhatMinhNKHs { get; set; }
    }
}
